apiVersion: apps/v1
kind: Deployment
metadata:
  name: rewind
  labels:
    app: rewind
spec:
  replicas: {{ .Values.workloads.rewind.replicaCount }}
  selector:
    matchLabels:
      app: rewind
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rewind
    spec:
      containers:
        - name: rewind
          image: ghcr.io/bayerhazard/rewind:1.3.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8765
              protocol: TCP
          env:
            - name: EXPORT_SCHEDULE
              value: {{ .Values.exportSchedule | default "03:00" | quote }}
          volumeMounts:
            - name: appdata
              mountPath: /Data
      volumes:
        - name: appdata
          hostPath:
            path: /olares/rootfs/userspace/pvc-userspace-aimighty-yxce0cmwdzqtayox/Data/rewind
            type: DirectoryOrCreate
