apiVersion: v1
kind: Service
metadata:
  name: rewind
  labels:
    app: rewind
spec:
  selector:
    app: rewind
  ports:
    - port: 8765
      targetPort: 8765
      protocol: TCP
  type: ClusterIP
